blog/article/urls.py
from django.urls import path
from article import views

app_name = 'article'
urlpatterns = [
    path('', views.article, name='article'),
    ]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include , re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='main')),
    path('article/', include('article.urls', namespace='article')),
    re_path('.*', views.main),
]

blog/main/urls.py
from django.urls import  path
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
    path('about/', views.about, name='about'),
    ]

blog/article/models.py
from django.db import models

# Create your models here.

blog/main/models.py
from django.db import models

# Create your models here.

blog/article/views.py
from django.shortcuts import render

def article(request):
    
    return render(request, 'article/article.html')

blog/main/views.py
from django.shortcuts import render

def main(request):
    context = { 'like' : 'Django很棒' }
    return render(request, 'main/main.html', context)
def about(request):
    return render(request, 'main/about.html')

blog/article/templates/article/article.html
<!doctype html>
{% load static %}
<html >
<head>
	<meta charset="UTF-8" />
	<title>部落格</title>
	<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h2>部落格說 --Hello world!</h2>
</body>
</html>

blog/main/templates/main/about.html
<!doctype html>
{% load static %}
<html>
<head>
	<meta charset="UTF-8" />
	<title>部落格</title>
	<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
	{% include 'main/menu.html' %}
	<h2>關於部落格</h2>
	<p>歡迎來到我的部落格,您可盡情瀏覽並留言</p>
</body>
</html>

blog/main/templates/main/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<title>部落格</title>
	<link rel = "stylesheet" href = "{% static 'main/css/main.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h2>部落格-- {% block heading %}{% endblock %}</h2>
<% block content %}{% endblock %}
</body>
</html>

blog/main/templates/main/main.html
<!doctype html>
{% load static %}
<html>
<head>
	<meta charset="UTF-8" />
	<title>部落格</title>
	<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
	{% include 'main/menu.html' %}
<h2>Django說這裡是首頁</h2>
</body>
</html>

blog/main/templates/main/menu.html
<ul id = "menu">
	<li><a href ="{% url 'main:main' %}">首頁</a></li>
	<li><a href ="{% url 'main:about' %}">關於</a>
	<li><a href = "{% url 'article:article' %}">部落格</a>
</ul>